//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianCommunication.Shared.OperationResult {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultEnumerationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultEnumerationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuardianCommunication.Shared.OperationResult.ResultEnumerationResource", typeof(ResultEnumerationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی در دیتابیس یافت نشد.
        /// </summary>
        public static string AccessLevelStatusAccessLevelNotFoundInDatabase {
            get {
                return ResourceManager.GetString("AccessLevelStatusAccessLevelNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان سطح دسترسی معتبر نمی باشد.
        /// </summary>
        public static string AccessLevelStatusAccessLevelTitleIsNotValid {
            get {
                return ResourceManager.GetString("AccessLevelStatusAccessLevelTitleIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی معتبر نمی باشد.
        /// </summary>
        public static string AccountingStatusAccessTypeIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusAccessTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری در اکتیودایرکتوری می بایست منحصر به فرد باشد.
        /// </summary>
        public static string AccountingStatusActiveDirectoryUsernameMustBeUnique {
            get {
                return ResourceManager.GetString("AccountingStatusActiveDirectoryUsernameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک کاربر ادمین می بایست در سیستم وجود داشته باشد.
        /// </summary>
        public static string AccountingStatusAtLeastOneSystemAdminMustExistInSystem {
            get {
                return ResourceManager.GetString("AccountingStatusAtLeastOneSystemAdminMustExistInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر کلمه عبور کاربر دیگری وجود ندارد.
        /// </summary>
        public static string AccountingStatusCanNotChangeAnotherUserPassword {
            get {
                return ResourceManager.GetString("AccountingStatusCanNotChangeAnotherUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر جاری در دیتابیس یافت نشد.
        /// </summary>
        public static string AccountingStatusCurrentUserNotFoundInDatabase {
            get {
                return ResourceManager.GetString("AccountingStatusCurrentUserNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور نمی تواند مساوی با نام کاربری باشد.
        /// </summary>
        public static string AccountingStatusPasswordCannotBeEqualToUsername {
            get {
                return ResourceManager.GetString("AccountingStatusPasswordCannotBeEqualToUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور معتبر نمی باشد.
        /// </summary>
        public static string AccountingStatusPasswordIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعالیت معتبر نمی باشد.
        /// </summary>
        public static string AccountingStatusUserActionActionCodeIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUserActionActionCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش های مجاز کاربر نباید تعیین شوند.
        /// </summary>
        public static string AccountingStatusUserEmployeesMustBeEmptyBeacuseOfUserRole {
            get {
                return ResourceManager.GetString("AccountingStatusUserEmployeesMustBeEmptyBeacuseOfUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل مجاز کاربر می بایست تعیین شوند.
        /// </summary>
        public static string AccountingStatusUserEmployeesMustHaveValueBeacuseOfUserRole {
            get {
                return ResourceManager.GetString("AccountingStatusUserEmployeesMustHaveValueBeacuseOfUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در سیستم فعال نمی باشد.
        /// </summary>
        public static string AccountingStatusUserIsNotActive {
            get {
                return ResourceManager.GetString("AccountingStatusUserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری معتبر نمی باشد.
        /// </summary>
        public static string AccountingStatusUsernameIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUsernameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری می بایست منحصر به فرد باشد.
        /// </summary>
        public static string AccountingStatusUsernameMustBeUnique {
            get {
                return ResourceManager.GetString("AccountingStatusUsernameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در دیتابیس یافت نشد.
        /// </summary>
        public static string AccountingStatusUserNotFoundInDatabase {
            get {
                return ResourceManager.GetString("AccountingStatusUserNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در حافظه یافت نشد.
        /// </summary>
        public static string AccountingStatusUserNotFoundUserCache {
            get {
                return ResourceManager.GetString("AccountingStatusUserNotFoundUserCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور قدیمی معتبر نمی باشد.
        /// </summary>
        public static string AccountingStatusUserOldPasswordIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUserOldPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ذخیره تنظیمات کاربری تعیین کد الزامی است.
        /// </summary>
        public static string AccountingStatusUserProfileSettingCodeIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUserProfileSettingCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ذخیره تنظیمات کاربری می بایست کد کاربر تعیین شود.
        /// </summary>
        public static string AccountingStatusUserProfileUserIdIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUserProfileUserIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل مجاز کاربر نباید تعیین شوند.
        /// </summary>
        public static string AccountingStatusUserSectionsMustBeEmptyBeacuseOfUserRole {
            get {
                return ResourceManager.GetString("AccountingStatusUserSectionsMustBeEmptyBeacuseOfUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش های مجاز کاربر می بایست تعیین شوند.
        /// </summary>
        public static string AccountingStatusUserSectionsMustHaveValueBeacuseOfUserRole {
            get {
                return ResourceManager.GetString("AccountingStatusUserSectionsMustHaveValueBeacuseOfUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور به درستی وارد نشده است.
        /// </summary>
        public static string AccountingStatusUserVerificationPasswordIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUserVerificationPasswordIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اتمام فعالیت کاربر سپری شده است.
        /// </summary>
        public static string AccountingStatusUserVerificationUserIsExpired {
            get {
                return ResourceManager.GetString("AccountingStatusUserVerificationUserIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در تاریخ و ساعت جاری مجاز به ورود به سیستم نمی باشد.
        /// </summary>
        public static string AccountingStatusUserVerificationUserIsNotAuthorizedAtThisDate {
            get {
                return ResourceManager.GetString("AccountingStatusUserVerificationUserIsNotAuthorizedAtThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مجاز به استفاده از این نرم افزار نمی باشد.
        /// </summary>
        public static string AccountingStatusUserVerificationUserIsNotValidForThisApplication {
            get {
                return ResourceManager.GetString("AccountingStatusUserVerificationUserIsNotValidForThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نما کاربر به درستی وارد نشده است.
        /// </summary>
        public static string AccountingStatusUserVerificationUsernameIsNotValid {
            get {
                return ResourceManager.GetString("AccountingStatusUserVerificationUsernameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل قطع کار شده است.
        /// </summary>
        public static string AccountingStatusUserVerificationUserRelatedEmployeeIsCuted {
            get {
                return ResourceManager.GetString("AccountingStatusUserVerificationUserRelatedEmployeeIsCuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه دسترسی می بایست دارای عنوان باشد.
        /// </summary>
        public static string AreaStatusAreaMustHaveTitle {
            get {
                return ResourceManager.GetString("AreaStatusAreaMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه دسترسی در پایگاه داده یافت نشد.
        /// </summary>
        public static string AreaStatusAreaNotFoundInDatabase {
            get {
                return ResourceManager.GetString("AreaStatusAreaNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد منطقه دسترسی تکراری است.
        /// </summary>
        public static string AreaStatusAreaNumberAlreadyExistInDatabase {
            get {
                return ResourceManager.GetString("AreaStatusAreaNumberAlreadyExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد منطقه دسترسی معتبر نمی باشد.
        /// </summary>
        public static string AreaStatusAreaNumberIsNotValid {
            get {
                return ResourceManager.GetString("AreaStatusAreaNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه دسترسی پدر معتبر نمی باشد و نمی تواند از بین فرزندان منطقه دسترسی جاری انتخاب شود.
        /// </summary>
        public static string AreaStatusParentAreaCanNotBeInNodeHeriarchy {
            get {
                return ResourceManager.GetString("AreaStatusParentAreaCanNotBeInNodeHeriarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه دسترسی می بایست دارای پدر معتبر باشد.
        /// </summary>
        public static string AreaStatusParentIsNotvalid {
            get {
                return ResourceManager.GetString("AreaStatusParentIsNotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع روز تقویم معتبر نمی باشد.
        /// </summary>
        public static string CalendarStatusDayStatusIsNotValid {
            get {
                return ResourceManager.GetString("CalendarStatusDayStatusIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف تردد ها از روی ساعت وجود ندارد، زیرا تمامی تردد ها با موفقیت ذخیره نشده اند.
        /// </summary>
        public static string CommunicationCannotClearDataBecauseAllAllRecordsNotSavedInDatabase {
            get {
                return ResourceManager.GetString("CommunicationCannotClearDataBecauseAllAllRecordsNotSavedInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان برقراری ارتباط با دستگاه وجود ندارد.
        /// </summary>
        public static string CommunicationStatusCannotConnect {
            get {
                return ResourceManager.GetString("CommunicationStatusCannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ارسال عکس کاربر وجود ندارد.
        /// </summary>
        public static string CommunicationStatusCannotSetUserPicture {
            get {
                return ResourceManager.GetString("CommunicationStatusCannotSetUserPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال برقرار شده است.
        /// </summary>
        public static string CommunicationStatusConnected {
            get {
                return ResourceManager.GetString("CommunicationStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا می بایست به دستگاه متصل شوید.
        /// </summary>
        public static string CommunicationStatusConnectTheDeviceFirst {
            get {
                return ResourceManager.GetString("CommunicationStatusConnectTheDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده های احراز هویت معتبر نمی باشد.
        /// </summary>
        public static string CommunicationStatusEnrollDataNotFound {
            get {
                return ResourceManager.GetString("CommunicationStatusEnrollDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دستگاه معتبر نمی باشد.
        /// </summary>
        public static string CommunicationStatusMachineNumberIsNotValid {
            get {
                return ResourceManager.GetString("CommunicationStatusMachineNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ تمپلیتی برای ذخیره سازی در دیتابیس یافت نشد.
        /// </summary>
        public static string CommunicationStatusNoTemplateExistForSaveInDatabase {
            get {
                return ResourceManager.GetString("CommunicationStatusNoTemplateExistForSaveInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تمپلیت برای ثبت در پایگاه داده باید مشخص شود.
        /// </summary>
        public static string CommunicationStatusNoTemplateTypeSelectedForInsertInDatabase {
            get {
                return ResourceManager.GetString("CommunicationStatusNoTemplateTypeSelectedForInsertInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این عملیات بر روی دستگاه انتخاب شده پشتیبانی نمی شود.
        /// </summary>
        public static string CommunicationStatusNotSupport {
            get {
                return ResourceManager.GetString("CommunicationStatusNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر های اتباطی معتبر نمی باشد.
        /// </summary>
        public static string CommunicationStatusParametersIsNotValid {
            get {
                return ResourceManager.GetString("CommunicationStatusParametersIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید کننده معتبر نمی باشد.
        /// </summary>
        public static string CommunicationStatusProducerIsNotActiveInSystem {
            get {
                return ResourceManager.GetString("CommunicationStatusProducerIsNotActiveInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به نوع .
        /// </summary>
        public static string CommunicationStatusRfCardNumberIdNotValidDueToVerificationStyle {
            get {
                return ResourceManager.GetString("CommunicationStatusRfCardNumberIdNotValidDueToVerificationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ساعت باید مشخص شود.
        /// </summary>
        public static string CommunicationStatusVirdiTerminalIdIsRequired {
            get {
                return ResourceManager.GetString("CommunicationStatusVirdiTerminalIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنل باید مشخص شود.
        /// </summary>
        public static string CommunicationStatusVirdiUserIdIsRequired {
            get {
                return ResourceManager.GetString("CommunicationStatusVirdiUserIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تردد پیش از این وجود دارد.
        /// </summary>
        public static string DataFileStatusDataFileAlreadyExist {
            get {
                return ResourceManager.GetString("DataFileStatusDataFileAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت پپرسنل معتبر نمی باشد.
        /// </summary>
        public static string DataFileStatusEmployeeNumberIsNotValid {
            get {
                return ResourceManager.GetString("DataFileStatusEmployeeNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیلی ناشناخته اطلاعات تردد در دیتابیس ثبت نشد.
        /// </summary>
        public static string DataFileStatusEverythingIsOkAboutDataFileButForUnknownReasonSaveIsNotSuccessful {
            get {
                return ResourceManager.GetString("DataFileStatusEverythingIsOkAboutDataFileButForUnknownReasonSaveIsNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع داده برای ثبت تردد معتبر نمی باشد.
        /// </summary>
        public static string DataFileStatusUserTypeIsNotValid {
            get {
                return ResourceManager.GetString("DataFileStatusUserTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DataFileStatusVerificationStyleIsNotValid {
            get {
                return ResourceManager.GetString("DataFileStatusVerificationStyleIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه مراجعه کننده معتبر نمی باشد.
        /// </summary>
        public static string DataFileStatusVisitorIdIsNotValid {
            get {
                return ResourceManager.GetString("DataFileStatusVisitorIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusAntiPassbackDurationOfEntranceIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusAntiPassbackDurationOfEntranceIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaudRate معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusBaudRateIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusBaudRateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پورت سریال معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusComPortIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusComPortIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس IP دستتگاه معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusDeviceIpIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusDeviceIpIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دستگاه در دیتابیس یافت نشد و یا شما مجاز به دسترسی به آن نیستید.
        /// </summary>
        public static string DeviceStatusDeviceNotFoundInDatabaseOrYouAreNotAuthorizedToAccessIt {
            get {
                return ResourceManager.GetString("DeviceStatusDeviceNotFoundInDatabaseOrYouAreNotAuthorizedToAccessIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره دستگاه معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusDeviceNumberIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusDeviceNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان در معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusDoorMustHaveTitle {
            get {
                return ResourceManager.GetString("DeviceStatusDoorMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در در دیتابیس یافت نشد.
        /// </summary>
        public static string DeviceStatusDoorNotFoundInDatabase {
            get {
                return ResourceManager.GetString("DeviceStatusDoorNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سماره در معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusDoorNumberIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusDoorNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusDoorSensorDelayIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusDoorSensorDelayIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusLockOpenDurationIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusLockOpenDurationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusMultiPersonOperationIntervalIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusMultiPersonOperationIntervalIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ زمان دسترسی در سیستم تعریف نشده است.
        /// </summary>
        public static string DeviceStatusNotTimeZoneDefinedInSystem {
            get {
                return ResourceManager.GetString("DeviceStatusNotTimeZoneDefinedInSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusOperateIntervalIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusOperateIntervalIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusPassageDelayIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusPassageDelayIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول در سیستم تعریف نشده است.
        /// </summary>
        public static string DeviceStatusProductNotFoundInDatbase {
            get {
                return ResourceManager.GetString("DeviceStatusProductNotFoundInDatbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پورت دستگاه معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusTcpPortIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusTcpPortIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان دستگاه معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusTitleIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusTitleIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع احراز هویت در معتبر نمی باشد.
        /// </summary>
        public static string DeviceStatusVerificationStyleIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusVerificationStyleIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeviceStatusWiegandFormatIsNotValid {
            get {
                return ResourceManager.GetString("DeviceStatusWiegandFormatIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در باید دارای عنوان باشد.
        /// </summary>
        public static string DoorStatusDoorMustHaveTitle {
            get {
                return ResourceManager.GetString("DoorStatusDoorMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در یافت نشد.
        /// </summary>
        public static string DoorStatusDoorNotFoundInDatabase {
            get {
                return ResourceManager.GetString("DoorStatusDoorNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضمیمه در دیتابیس یافت نشد.
        /// </summary>
        public static string EmployeeAttachmentStatusAttachmentNotFoundInDatabase {
            get {
                return ResourceManager.GetString("EmployeeAttachmentStatusAttachmentNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ضمیمه معتبر نمی باشد.
        /// </summary>
        public static string EmployeeAttachmentStatusEmployeeAttachmentTypeIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeAttachmentStatusEmployeeAttachmentTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف تعداد پرسنل مجاز رعایت نشده است.
        /// </summary>
        public static string EmployeeLimit {
            get {
                return ResourceManager.GetString("EmployeeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پرسنلی می بایست منحصر به فرد باشد.
        /// </summary>
        public static string EmployeeStatusActiveDirectoryEmployeeNumberMustBeUnique {
            get {
                return ResourceManager.GetString("EmployeeStatusActiveDirectoryEmployeeNumberMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل می بایست دارای تاریخ پایان باشد.
        /// </summary>
        public static string EmployeeStatusCutEmployeeMustHaveEndDate {
            get {
                return ResourceManager.GetString("EmployeeStatusCutEmployeeMustHaveEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل پرسنل معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmailIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان استخدام می بایست بزرگتر از تاریخ شروع آن باشد.
        /// </summary>
        public static string EmployeeStatusEmpDateMustBeGreaterThanEndDate {
            get {
                return ResourceManager.GetString("EmployeeStatusEmpDateMustBeGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استاندارد معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeEnrollDataEnrollStandardIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeEnrollDataEnrollStandardIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید کننده معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeEnrollDataProducerNumberIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeEnrollDataProducerNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع احراز هویت معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeEnrollDataVerificationStyleIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeEnrollDataVerificationStyleIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل در دیتابیس یافت نشد و یا شما مجاز به دسترسی به آن نیستید.
        /// </summary>
        public static string EmployeeStatusEmployeeNotFoundInDatabaseOrYouAreNotAuthorizedToAccessIt {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeNotFoundInDatabaseOrYouAreNotAuthorizedToAccessIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پرسنلی معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeNumberIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات اثر انگشت و یا چهره معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeTemplateBinaryDataIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeTemplateBinaryDataIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استاندارد اثر انگشت و یا چهره معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeTemplateEnrollStandardIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeTemplateEnrollStandardIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اثر انگشت و یا چهره معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeTemplateEnrollTypeIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeTemplateEnrollTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تولید کننده اثر انگشت و یا چهره معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusEmployeeTemplateProducerNumberIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusEmployeeTemplateProducerNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پرسنل معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusFirstNameIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusFirstNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی پرسنل معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusLastNameIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusLastNameIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره ملی معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusNationalIdIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusNationalIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اتمام اعتبار کارت معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusRfCardDateExpireIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusRfCardDateExpireIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کارت معتبر نمی باشد.
        /// </summary>
        public static string EmployeeStatusRfCardRfCardDataIsNotValid {
            get {
                return ResourceManager.GetString("EmployeeStatusRfCardRfCardDataIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات احراز هویت در دیتابیس یافت نشد و یا شما مجاز به دسترسی به آن نمی باشید.
        /// </summary>
        public static string EmployeeStatusRfCardStatusRfCardNotFoundOrYouAreNotAuthorizedToAccessIt {
            get {
                return ResourceManager.GetString("EmployeeStatusRfCardStatusRfCardNotFoundOrYouAreNotAuthorizedToAccessIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تغییر در انواع استخدام پیش فرض سیستم وجود ندارد.
        /// </summary>
        public static string EmploymentTypeStatusCanNotAddOrRemoveSystemFixedEmpType {
            get {
                return ResourceManager.GetString("EmploymentTypeStatusCanNotAddOrRemoveSystemFixedEmpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع استخدام می بایست دارای عنوان باشد.
        /// </summary>
        public static string EmploymentTypeStatusEmploymentTypeMustHaveTitle {
            get {
                return ResourceManager.GetString("EmploymentTypeStatusEmploymentTypeMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع استخدام معتبر نمی باشد.
        /// </summary>
        public static string EmploymentTypeStatusEmploymentTypeNumberIsNotValid {
            get {
                return ResourceManager.GetString("EmploymentTypeStatusEmploymentTypeNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع استخدام پیش از این در دیتابیس وجود دارد.
        /// </summary>
        public static string EmploymentTypeStatusEmplTypeNumberAlreadyExistInDatabase {
            get {
                return ResourceManager.GetString("EmploymentTypeStatusEmplTypeNumberAlreadyExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع استخدام در دیتابیس یافت نشد.
        /// </summary>
        public static string EmploymentTypeStatusEmpTypeNotFoundInDatabase {
            get {
                return ResourceManager.GetString("EmploymentTypeStatusEmpTypeNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مجاز به درسترسی به بخش جاری نمی باشد.
        /// </summary>
        public static string GeneralAccessDenied {
            get {
                return ResourceManager.GetString("GeneralAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات نرم افزار درخواست دهنده معتبر نمی باشد.
        /// </summary>
        public static string GeneralApplicationIsNotValid {
            get {
                return ResourceManager.GetString("GeneralApplicationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در رابطه های دیتایس.
        /// </summary>
        public static string GeneralDatabaseHasForeignKeyConstraint {
            get {
                return ResourceManager.GetString("GeneralDatabaseHasForeignKeyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در اتصال به دیتابیس.
        /// </summary>
        public static string GeneralDatabaseLogOnFailed {
            get {
                return ResourceManager.GetString("GeneralDatabaseLogOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکل در اتصال به دیتابیس.
        /// </summary>
        public static string GeneralDatabaseNotAvailable {
            get {
                return ResourceManager.GetString("GeneralDatabaseNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخلف از بازه زمانی مجاز برای اتصال به دیتابیس.
        /// </summary>
        public static string GeneralDatabaseRequestTimeout {
            get {
                return ResourceManager.GetString("GeneralDatabaseRequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف تعداد حرف مجاز رعایت نشده است.
        /// </summary>
        public static string GeneralDatabaseStringOrBinaryMustBeTruncated {
            get {
                return ResourceManager.GetString("GeneralDatabaseStringOrBinaryMustBeTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده تکراری.
        /// </summary>
        public static string GeneralDatabaseUniqueKeyConstraint {
            get {
                return ResourceManager.GetString("GeneralDatabaseUniqueKeyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی باعث راه اندازی مجدد سیستم Cache گردید.
        /// </summary>
        public static string GeneralFaultCausedCacheDataReset {
            get {
                return ResourceManager.GetString("GeneralFaultCausedCacheDataReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به انجام این عملیات نیستیتد.
        /// </summary>
        public static string GeneralNotAuthorized {
            get {
                return ResourceManager.GetString("GeneralNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این عملیات پشتیبانی نمی شود.
        /// </summary>
        public static string GeneralNotSupported {
            get {
                return ResourceManager.GetString("GeneralNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارتباط با پایگاه داده.
        /// </summary>
        public static string GeneralObjectDatabaseNotAvailable {
            get {
                return ResourceManager.GetString("GeneralObjectDatabaseNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آیتم دارای وابسیتگی هایی در سیستم است.
        /// </summary>
        public static string GeneralObjectHasForeignKeyConstraint {
            get {
                return ResourceManager.GetString("GeneralObjectHasForeignKeyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ مقداری به پارامتر نسبت داده نشده است.
        /// </summary>
        public static string GeneralObjectIsNull {
            get {
                return ResourceManager.GetString("GeneralObjectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارتباط با پایگاه داده.
        /// </summary>
        public static string GeneralObjectLogOnFailed {
            get {
                return ResourceManager.GetString("GeneralObjectLogOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخطی از زمان مجاز برای عملیات.
        /// </summary>
        public static string GeneralObjectRequestTimeout {
            get {
                return ResourceManager.GetString("GeneralObjectRequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول رسته بیش از حد مجاز است.
        /// </summary>
        public static string GeneralObjectUniqueKeyConstraint {
            get {
                return ResourceManager.GetString("GeneralObjectUniqueKeyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقیقه می بایست بین 0 تا 59 باشد.
        /// </summary>
        public static string GeneralPropertValueIsNotValid {
            get {
                return ResourceManager.GetString("GeneralPropertValueIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربر جاری معتبر نمی باشد.
        /// </summary>
        public static string GeneralUserInfoIsNotValid {
            get {
                return ResourceManager.GetString("GeneralUserInfoIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرک تحصیلی می بایست دارای عنوان باشد.
        /// </summary>
        public static string GradeStatusGradeMustHaveTitle {
            get {
                return ResourceManager.GetString("GradeStatusGradeMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرک تحصیلی در دیتابیس یافت نشد.
        /// </summary>
        public static string GradeStatusGradeNotFoundInDatabase {
            get {
                return ResourceManager.GetString("GradeStatusGradeNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مدرک تحصیلی قبلا تعریف شده است.
        /// </summary>
        public static string GradeStatusGradeNumberAlreadyExistInDatabase {
            get {
                return ResourceManager.GetString("GradeStatusGradeNumberAlreadyExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مدرک تحصیلی معتبر نمی باشد.
        /// </summary>
        public static string GradeStatusGradeNumberIsNotValid {
            get {
                return ResourceManager.GetString("GradeStatusGradeNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت می بایست دارای عنوان باشد.
        /// </summary>
        public static string PositionStatusPositionMustHaveTitle {
            get {
                return ResourceManager.GetString("PositionStatusPositionMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت در دیتابیس یافت نشد.
        /// </summary>
        public static string PositionStatusPositionNotFoundInDatabase {
            get {
                return ResourceManager.GetString("PositionStatusPositionNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد سمت قبلا تعریف شده است.
        /// </summary>
        public static string PositionStatusPositionNumberAlreadyExistInDatabase {
            get {
                return ResourceManager.GetString("PositionStatusPositionNumberAlreadyExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سمت معتبر نمی باشد.
        /// </summary>
        public static string PositionStatusPositionNumberIsNotValid {
            get {
                return ResourceManager.GetString("PositionStatusPositionNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بخش پدر معتبر نمی باشد.
        /// </summary>
        public static string SectionStatusParentIsNotvalid {
            get {
                return ResourceManager.GetString("SectionStatusParentIsNotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بخش پدر می بایست متفاوت از کد بخش باشد.
        /// </summary>
        public static string SectionStatusParentIsSameAsSectionCode {
            get {
                return ResourceManager.GetString("SectionStatusParentIsSameAsSectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش پدر معتبر نمی باشد و نمی تواند از بین فرزندان بخش جاری انتخاب شود.
        /// </summary>
        public static string SectionStatusParentSectionCanNotBeInNodeHeriarchy {
            get {
                return ResourceManager.GetString("SectionStatusParentSectionCanNotBeInNodeHeriarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مدیر بخش معتبر نمی باشد.
        /// </summary>
        public static string SectionStatusSectionManagerEmployeeNumberIsNotvalid {
            get {
                return ResourceManager.GetString("SectionStatusSectionManagerEmployeeNumberIsNotvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش می بایست دارای عنوان باشد.
        /// </summary>
        public static string SectionStatusSectionMustHaveTitle {
            get {
                return ResourceManager.GetString("SectionStatusSectionMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش در حافظه سیستم یافت نشد.
        /// </summary>
        public static string SectionStatusSectionNotFoundInCache {
            get {
                return ResourceManager.GetString("SectionStatusSectionNotFoundInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بخش در دیتابیس یافت نشد و یا شما مجاز به دسترسی به آن نمی باشید.
        /// </summary>
        public static string SectionStatusSectionNotFoundInDatabaseeOrYouAreNotAuthorizedToAccessIt {
            get {
                return ResourceManager.GetString("SectionStatusSectionNotFoundInDatabaseeOrYouAreNotAuthorizedToAccessIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بخش قبلا تعریف شده است.
        /// </summary>
        public static string SectionStatusSectionNumberAlreadyExistInDatabase {
            get {
                return ResourceManager.GetString("SectionStatusSectionNumberAlreadyExistInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد بخش معتبر نمی باشد.
        /// </summary>
        public static string SectionStatusSectionNumberIsNotValid {
            get {
                return ResourceManager.GetString("SectionStatusSectionNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات موفقیت امیز انجام شد.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب در دیتابیس یافت نشد.
        /// </summary>
        public static string TagStatusNotFoundInDatabase {
            get {
                return ResourceManager.GetString("TagStatusNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد برچسب معتبر نمی باشد.
        /// </summary>
        public static string TagStatusTagNumberIsNotValid {
            get {
                return ResourceManager.GetString("TagStatusTagNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان برچسب معتبر نمی باشد.
        /// </summary>
        public static string TagStatusTagTitleIsNotValid {
            get {
                return ResourceManager.GetString("TagStatusTagTitleIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار برچسب در دیتابیس یافت نشد.
        /// </summary>
        public static string TagValueStatusNotFoundInDatabase {
            get {
                return ResourceManager.GetString("TagValueStatusNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد برچسب معتبر نمی باشد.
        /// </summary>
        public static string TagValueStatusTagNumberIsNotValid {
            get {
                return ResourceManager.GetString("TagValueStatusTagNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار برچسب می بایست منحصر به فرد باشد.
        /// </summary>
        public static string TagValueStatusTagNumberMustBeUnique {
            get {
                return ResourceManager.GetString("TagValueStatusTagNumberMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار برچسب معتبر نمی باشد.
        /// </summary>
        public static string TagValueStatusValueOfIsNotValid {
            get {
                return ResourceManager.GetString("TagValueStatusValueOfIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای یک بازه زمانی می بایست هم ساعت شروع و هم یاعت پایان مشخص شود.
        /// </summary>
        public static string TimeZoneStatusBothIntervalStartAndEndDateOfIntervalMustBeHaveValue {
            get {
                return ResourceManager.GetString("TimeZoneStatusBothIntervalStartAndEndDateOfIntervalMustBeHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز بازه دسترسی معتبر نمی باشد.
        /// </summary>
        public static string TimeZoneStatusIntervalDayTypeIsNotValid {
            get {
                return ResourceManager.GetString("TimeZoneStatusIntervalDayTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت پایان بازه دسترسی معتبر نمی باشد.
        /// </summary>
        public static string TimeZoneStatusIntervalEndIsNotValid {
            get {
                return ResourceManager.GetString("TimeZoneStatusIntervalEndIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعت شروع بازه دسترسی معتبر نمی باشد.
        /// </summary>
        public static string TimeZoneStatusIntervalStartIsNotValid {
            get {
                return ResourceManager.GetString("TimeZoneStatusIntervalStartIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه زمانی می بایست حداقل دارای یک روز باشد.
        /// </summary>
        public static string TimeZoneStatusTimeZoneMustHaveAtLeaseOnInterval {
            get {
                return ResourceManager.GetString("TimeZoneStatusTimeZoneMustHaveAtLeaseOnInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه زمانی می بایست دارای عنوان باشد.
        /// </summary>
        public static string TimeZoneStatusTimeZoneMustHaveTitle {
            get {
                return ResourceManager.GetString("TimeZoneStatusTimeZoneMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه زمانی در پایگاه داده یافت نشد.
        /// </summary>
        public static string TimeZoneStatusTimeZoneNotFoundInDatabase {
            get {
                return ResourceManager.GetString("TimeZoneStatusTimeZoneNotFoundInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای هر روز در بازه زمانی تنها یک رکورد می تواد وجود داشته باشد.
        /// </summary>
        public static string TimeZoneStatusZoneMustHaveUniqueDayTypeInterval {
            get {
                return ResourceManager.GetString("TimeZoneStatusZoneMustHaveUniqueDayTypeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته در سیستم رخ داده است.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ خروج مراجعه کننده می بایست بزرگتر از تاریخ ورود باشد.
        /// </summary>
        public static string VisitorStatusExitDateMustBeGreaterThanEnteranceDate {
            get {
                return ResourceManager.GetString("VisitorStatusExitDateMustBeGreaterThanEnteranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده می بایست دارای شماره کارت باشد.
        /// </summary>
        public static string VisitorStatusVisitorMustHaveCardNumber {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorMustHaveCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده می بایست دارای تاریخ خروج باشد.
        /// </summary>
        public static string VisitorStatusVisitorMustHaveExitDate {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorMustHaveExitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده می بایست دارای اطلاعات ارحراز هویت از نوع چهره باشد.
        /// </summary>
        public static string VisitorStatusVisitorMustHaveFaceData {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorMustHaveFaceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده می بایست دارای اطلاعات احراز هویت از نوع اثرانگشت باشد.
        /// </summary>
        public static string VisitorStatusVisitorMustHaveFingerData {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorMustHaveFingerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده می بایست دارای نام باشد.
        /// </summary>
        public static string VisitorStatusVisitorMustHaveFirstName {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorMustHaveFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده می بایست دارای نام خانوادگی باشد.
        /// </summary>
        public static string VisitorStatusVisitorMustHaveLastName {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorMustHaveLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعه کننده در دیتابیس یافت نشد.
        /// </summary>
        public static string VisitorStatusVisitorNotFoundInDatabase {
            get {
                return ResourceManager.GetString("VisitorStatusVisitorNotFoundInDatabase", resourceCulture);
            }
        }
    }
}
