syntax = "proto3";
package padis.controller;

enum PadisControllerGrpcMessageType {
  SendCommand = 0;
  ResponseCommand = 1;
  GetDeviceConfigs = 2;
  DeviceEvent = 3;
  DeviceAttendance = 4;
  MatchOnServer = 5;
  MatchOnServerResponse = 6;
  Heartbeat = 7;
  Ack = 8;
}

message PadisControllerGrpcMessage {
  string device_serial_number = 1;								
  string message_id = 2;								
  PadisControllerGrpcMessageType message_type = 3;	
  string message_content = 4;	
  int32 error_code = 5;
}

service PadisControllerGrpcService {
  rpc Stream (stream PadisControllerGrpcMessage) returns (stream PadisControllerGrpcMessage);
}
